<?php
namespace Kitmage\Tutor\Entitlements\WooCommerce;
final class ProductSettings {
	public static function register(){add_filter('woocommerce_product_data_tabs',array(__CLASS__,'tab'));add_action('woocommerce_product_data_panels',array(__CLASS__,'panel'));add_action('woocommerce_admin_process_product_object',array(__CLASS__,'save'));add_action('woocommerce_product_after_variable_attributes',array(__CLASS__,'variation'),10,3);add_action('woocommerce_save_product_variation',array(__CLASS__,'save_variation'),10,2);}
	public static function tab($tabs){$tabs['kte']=array('label'=>__('Training Entitlements','tutor'),'target'=>'kte_product_data','class'=>array('show_if_simple','show_if_variable','show_if_subscription','show_if_variable-subscription'));return $tabs;}
	private static function courses(){return get_posts(array('post_type'=>'courses','posts_per_page'=>100,'meta_key'=>'_tutor_course_price_type','meta_value'=>'entitlement','orderby'=>'title','order'=>'ASC'));}
	public static function panel(){echo '<div id="kte_product_data" class="panel woocommerce_options_panel hidden">';woocommerce_wp_checkbox(array('id'=>'_kte_enabled','label'=>__('Enable Training Entitlements','tutor')));echo '<p class="form-field"><label for="_kte_course_id">'.esc_html__('Tutor LMS Course','tutor').'</label><select class="wc-enhanced-select" name="_kte_course_id" id="_kte_course_id"><option value="">'.esc_html__('Select a course','tutor').'</option>';foreach(self::courses() as $c)printf('<option value="%d" %s>%s</option>',$c->ID,selected((int)get_post_meta(get_the_ID(),'_kte_course_id',true),$c->ID,false),esc_html($c->post_title));echo '</select></p>';woocommerce_wp_text_input(array('id'=>'_kte_seats_per_unit','label'=>__('Entitlements Per Unit','tutor'),'type'=>'number','custom_attributes'=>array('min'=>'1','step'=>'1')));woocommerce_wp_text_input(array('id'=>'_kte_redemption_days','label'=>__('Redemption Window (days)','tutor'),'type'=>'number','value'=>get_post_meta(get_the_ID(),'_kte_redemption_days',true)?:30,'custom_attributes'=>array('min'=>'1','step'=>'1')));echo '</div>';}
	public static function save($p){$p->update_meta_data('_kte_enabled',isset($_POST['_kte_enabled'])?'yes':'no');foreach(array('_kte_course_id','_kte_seats_per_unit','_kte_redemption_days') as $k)$p->update_meta_data($k,absint($_POST[$k]??0));}
	public static function variation($loop,$data,$variation){echo '<div class="form-row form-row-full"><strong>'.esc_html__('Training Entitlement Overrides','tutor').'</strong></div>';woocommerce_wp_select(array('id'=>"_kte_course_id_$loop",'name'=>"_kte_course_id[$loop]",'label'=>__('Tutor course','tutor'),'value'=>get_post_meta($variation->ID,'_kte_course_id',true),'options'=>array(''=>__('Inherit','tutor'))+wp_list_pluck(self::courses(),'post_title','ID')));foreach(array('_kte_seats_per_unit'=>__('Seats per unit','tutor'),'_kte_redemption_days'=>__('Redemption days','tutor')) as $k=>$label)woocommerce_wp_text_input(array('id'=>"{$k}_$loop",'name'=>"{$k}[$loop]",'label'=>$label,'type'=>'number','value'=>get_post_meta($variation->ID,$k,true),'custom_attributes'=>array('min'=>'1','step'=>'1')));}
	public static function save_variation($id,$i){foreach(array('_kte_course_id','_kte_seats_per_unit','_kte_redemption_days') as $k){$v=absint($_POST[$k][$i]??0);if($v)update_post_meta($id,$k,$v);else delete_post_meta($id,$k);}}
}
