<?php
namespace Kitmage\Tutor\Entitlements\Admin;
use Kitmage\Tutor\Entitlements\Repository\AuditRepository;
use Kitmage\Tutor\Entitlements\Repository\BatchRepository;
final class Menu {
	const CAP='manage_woocommerce';public static function register(){add_action('admin_menu',static function(){add_submenu_page('woocommerce',__('Training Entitlements','tutor'),__('Training Entitlements','tutor'),self::CAP,'kitmage-training-entitlements',array(__CLASS__,'render'));});add_action('admin_post_kte_batch_action',array(__CLASS__,'action'));}
	public static function action(){if(!current_user_can(self::CAP))wp_die(esc_html__('Forbidden','tutor'),'',array('response'=>403));$id=absint($_POST['batch_id']??0);check_admin_referer('kte_batch_'.$id);$repo=new BatchRepository();$b=$repo->get($id);if(!$b)wp_die(esc_html__('Batch not found','tutor'));$action=sanitize_key($_POST['batch_action']??'');global $wpdb;$new=null;if('revoke'===$action)$new='revoked';elseif('reactivate'===$action&&'refunded'!==$b->status&&strtotime($b->expires_at)>current_time('timestamp',true)&&$b->entitlements_used+$b->entitlements_reserved<$b->entitlements_total)$new='active';if($new){$wpdb->update($wpdb->prefix.'kte_batches',array('status'=>$new,'updated_at'=>current_time('mysql',true)),array('id'=>$id));(new AuditRepository())->add($id,$action,$b->status,$new);if('revoke'===$action)do_action('kitmage_training_entitlements/batch_revoked',$id);}elseif('regenerate'===$action)$repo->regenerate_token($id);elseif('update'===$action){$total=absint($_POST['total']??0);$expires=sanitize_text_field($_POST['expires_at']??'');if($total>=$b->entitlements_used+$b->entitlements_reserved&&strtotime($expires)){$wpdb->update($wpdb->prefix.'kte_batches',array('entitlements_total'=>$total,'expires_at'=>gmdate('Y-m-d H:i:s',strtotime($expires)),'updated_at'=>current_time('mysql',true)),array('id'=>$id));(new AuditRepository())->add($id,'batch_update',array('total'=>$b->entitlements_total,'expires'=>$b->expires_at),array('total'=>$total,'expires'=>$expires));}}wp_safe_redirect(admin_url('admin.php?page=kitmage-training-entitlements&batch_id='.$id));exit;}
	public static function render(){if(!current_user_can(self::CAP))return;$id=absint($_GET['batch_id']??0);if($id){self::detail($id);return;}global $wpdb;$status=sanitize_key($_GET['status']??'');$page=max(1,absint($_GET['paged']??1));$where=$status?$wpdb->prepare(' WHERE status=%s',$status):'';$rows=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}kte_batches $where ORDER BY id DESC LIMIT 50 OFFSET ".(($page-1)*50));echo '<div class="wrap"><h1>'.esc_html__('Training Entitlements','tutor').'</h1><table class="widefat striped"><thead><tr><th>ID</th><th>'.esc_html__('Purchaser','tutor').'</th><th>'.esc_html__('Course','tutor').'</th><th>'.esc_html__('Order / Subscription','tutor').'</th><th>'.esc_html__('Seats','tutor').'</th><th>'.esc_html__('Expiration','tutor').'</th><th>'.esc_html__('Status','tutor').'</th></tr></thead><tbody>';foreach($rows as $b){$u=get_userdata($b->customer_user_id);echo '<tr><td><a href="'.esc_url(admin_url('admin.php?page=kitmage-training-entitlements&batch_id='.$b->id)).'">'.(int)$b->id.'</a></td><td>'.esc_html($u?$u->display_name:'#'.$b->customer_user_id).'</td><td>'.esc_html(get_the_title($b->course_id)?:'#'.$b->course_id).'</td><td>'.(int)$b->order_id.' / '.(int)$b->subscription_id.'</td><td>'.(int)$b->entitlements_used.' / '.(int)$b->entitlements_total.'</td><td>'.esc_html($b->expires_at).'</td><td>'.esc_html($b->status).'</td></tr>';}echo '</tbody></table></div>';}
	private static function detail($id){$b=(new BatchRepository())->get($id);if(!$b){echo '<div class="wrap"><p>'.esc_html__('Batch not found.','tutor').'</p></div>';return;}global $wpdb;$red=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}kte_redemptions WHERE batch_id=%d ORDER BY id",$id));$audit=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}kte_audit_log WHERE batch_id=%d ORDER BY id DESC",$id));echo '<div class="wrap"><h1>'.esc_html(sprintf(__('Entitlement Batch #%d','tutor'),$id)).'</h1><pre>'.esc_html(wp_json_encode($b,JSON_PRETTY_PRINT)).'</pre><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="kte_batch_action"><input type="hidden" name="batch_id" value="'.$id.'">';wp_nonce_field('kte_batch_'.$id);echo '<button class="button" name="batch_action" value="revoke">'.esc_html__('Revoke','tutor').'</button> <button class="button" name="batch_action" value="reactivate">'.esc_html__('Reactivate','tutor').'</button> <button class="button" name="batch_action" value="regenerate">'.esc_html__('Regenerate token','tutor').'</button><p><input type="number" min="'.(int)($b->entitlements_used+$b->entitlements_reserved).'" name="total" value="'.(int)$b->entitlements_total.'"> <input name="expires_at" value="'.esc_attr($b->expires_at).'"> <button class="button button-primary" name="batch_action" value="update">'.esc_html__('Update','tutor').'</button></p></form><h2>'.esc_html__('Redemptions','tutor').'</h2><pre>'.esc_html(wp_json_encode($red,JSON_PRETTY_PRINT)).'</pre><h2>'.esc_html__('Audit history','tutor').'</h2><pre>'.esc_html(wp_json_encode($audit,JSON_PRETTY_PRINT)).'</pre></div>';}
}
